// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.10
//   protoc               v6.33.4
// source: parser.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "parser";

/**
 * Image handling for the markdown emitter.
 *
 * * OFF — strip image references entirely.
 * * PLACEHOLDER (default) — emit `![](image_pN_K.png)` references in
 *   reading order at each image's y position, but do not extract or
 *   return pixel bytes. Keeps response size small while letting the LLM see
 *   where figures live in the document.
 * * EMBED — same references, plus bytes returned via `ParseResult.images`.
 *   Opt-in because pixel bytes can dwarf the text payload on image-heavy
 *   PDFs. (Bytes plumbing lands in stage 11b — current variant is parsed but
 *   behaves like PLACEHOLDER until then.)
 */
export enum ImageMode {
  IMAGE_MODE_UNSPECIFIED = 0,
  IMAGE_MODE_OFF = 1,
  IMAGE_MODE_PLACEHOLDER = 2,
  IMAGE_MODE_EMBED = 3,
  UNRECOGNIZED = -1,
}

export function imageModeFromJSON(object: any): ImageMode {
  switch (object) {
    case 0:
    case "IMAGE_MODE_UNSPECIFIED":
      return ImageMode.IMAGE_MODE_UNSPECIFIED;
    case 1:
    case "IMAGE_MODE_OFF":
      return ImageMode.IMAGE_MODE_OFF;
    case 2:
    case "IMAGE_MODE_PLACEHOLDER":
      return ImageMode.IMAGE_MODE_PLACEHOLDER;
    case 3:
    case "IMAGE_MODE_EMBED":
      return ImageMode.IMAGE_MODE_EMBED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ImageMode.UNRECOGNIZED;
  }
}

export function imageModeToJSON(object: ImageMode): string {
  switch (object) {
    case ImageMode.IMAGE_MODE_UNSPECIFIED:
      return "IMAGE_MODE_UNSPECIFIED";
    case ImageMode.IMAGE_MODE_OFF:
      return "IMAGE_MODE_OFF";
    case ImageMode.IMAGE_MODE_PLACEHOLDER:
      return "IMAGE_MODE_PLACEHOLDER";
    case ImageMode.IMAGE_MODE_EMBED:
      return "IMAGE_MODE_EMBED";
    case ImageMode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Supported output formats. */
export enum OutputFormat {
  OUTPUT_FORMAT_UNSPECIFIED = 0,
  OUTPUT_FORMAT_JSON = 1,
  OUTPUT_FORMAT_TEXT = 2,
  OUTPUT_FORMAT_MARKDOWN = 3,
  UNRECOGNIZED = -1,
}

export function outputFormatFromJSON(object: any): OutputFormat {
  switch (object) {
    case 0:
    case "OUTPUT_FORMAT_UNSPECIFIED":
      return OutputFormat.OUTPUT_FORMAT_UNSPECIFIED;
    case 1:
    case "OUTPUT_FORMAT_JSON":
      return OutputFormat.OUTPUT_FORMAT_JSON;
    case 2:
    case "OUTPUT_FORMAT_TEXT":
      return OutputFormat.OUTPUT_FORMAT_TEXT;
    case 3:
    case "OUTPUT_FORMAT_MARKDOWN":
      return OutputFormat.OUTPUT_FORMAT_MARKDOWN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OutputFormat.UNRECOGNIZED;
  }
}

export function outputFormatToJSON(object: OutputFormat): string {
  switch (object) {
    case OutputFormat.OUTPUT_FORMAT_UNSPECIFIED:
      return "OUTPUT_FORMAT_UNSPECIFIED";
    case OutputFormat.OUTPUT_FORMAT_JSON:
      return "OUTPUT_FORMAT_JSON";
    case OutputFormat.OUTPUT_FORMAT_TEXT:
      return "OUTPUT_FORMAT_TEXT";
    case OutputFormat.OUTPUT_FORMAT_MARKDOWN:
      return "OUTPUT_FORMAT_MARKDOWN";
    case OutputFormat.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Configuration for LiteParse document parsing. */
export interface LiteParseConfig {
  /** OCR language code (Tesseract format: "eng", "fra", "deu", etc.). */
  ocrLanguage: string;
  /** Whether OCR is enabled. When true, runs on text-sparse pages and embedded images. */
  ocrEnabled: boolean;
  /** HTTP OCR server URL (uses Tesseract if not provided) */
  ocrServerUrl?: string | undefined;
  /**
   * Extra HTTP headers sent with every request to `ocr_server_url`.
   * Ignored when `ocr_server_url` is unset.
   */
  ocrServerHeaders: HttpHeader[];
  /** Path to tessdata directory. Falls back to TESSDATA_PREFIX env var if not set. */
  tessdataPath?: string | undefined;
  /** Maximum number of pages to parse. */
  maxPages: number;
  /** Specific pages to parse (e.g., "1-5,10,15-20"). Unset means all pages. */
  targetPages?: string | undefined;
  /** DPI for rendering pages (used for OCR and screenshots). */
  dpi: number;
  /** Output format. */
  outputFormat: OutputFormat;
  /** Keep very small text that would normally be filtered out. */
  preserveVerySmallText: boolean;
  /** Password for encrypted/protected documents. */
  password?: string | undefined;
  /** Suppress progress output. */
  quiet: boolean;
  /** Number of concurrent OCR workers. Defaults to (number of CPU cores - 1), minimum 1. */
  numWorkers: number;
  /**
   * Controls how raster images are surfaced in markdown output. Has no
   * effect on JSON / text outputs.
   */
  imageMode: ImageMode;
  /**
   * Extract hyperlink annotations and render them as `[text](url)` in
   * markdown output. Default on. Disable for benchmark parity with
   * plain-text ground truth (the GT corpora never use link syntax).
   */
  extractLinks: boolean;
  /**
   * Whether a systemic OCR failure (every OCR task failed *and* at least one
   * was a text-sparse page whose primary text source was OCR) aborts the
   * whole parse. Default `true`: surface the root cause instead of silently
   * emitting blank pages. Set `false` to keep already-recovered native text
   * and return partial results when OCR is unavailable — useful for callers
   * that prefer a degraded document over a hard failure (e.g. when the host
   * has its own OCR fallback or treats OCR as best-effort enrichment).
   */
  ocrFailureFatal: boolean;
  /**
   * OCR request-hedging schedule (milliseconds) for the HTTP OCR engine.
   * Empty (default) = no hedging. With multiple delays (e.g.
   * `[0, 5000, 10000, 15000, 20000]`), each OCR attempt fires a duplicate
   * request at every delay and takes the first to succeed — trading extra
   * OCR-server load for lower tail latency on a slow/stuck pod. No effect on
   * the Tesseract engine.
   */
  ocrHedgeDelaysMs: number[];
  /**
   * Emit per-word sub-boxes on each `TextItem` (`TextItem.words`). Default
   * `false`: a text item already carries its own box, and word boxes roughly
   * double the text-item payload (size + napi marshalling), so they are only
   * worth computing for callers doing word-level bbox attribution. When
   * `false`, `TextItem.words` is always empty and the per-word tracking is
   * skipped entirely (zero allocation).
   */
  emitWordBoxes: boolean;
}

/** A single HTTP header as a name/value pair. */
export interface HttpHeader {
  name: string;
  value: string;
}

/** Request to parse a file. */
export interface ParseRequest {
  file: Buffer;
  config?: LiteParseConfig | undefined;
}

/** Request to screenshot the pages of a file. */
export interface ScreenshotRequest {
  file: Buffer;
  config?: LiteParseConfig | undefined;
}

export interface TextItem {
  text: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ParsedPage {
  pageNumber: number;
  pageWidth: number;
  pageHeight: number;
  textItems: TextItem[];
}

/** Response with a parsed file */
export interface ParseResponse {
  text: string;
  pages: ParsedPage[];
}

export interface ScreenshotPage {
  imageBytes: Buffer;
  pageNumber: number;
  height: number;
  width: number;
  mimeType: string;
}

/** Screenshot response for a PDF file */
export interface ScreenshotResponse {
  screenshots: ScreenshotPage[];
}

/** Request to estimate the complexity of a file. */
export interface IsComplexRequest {
  file: Buffer;
  config?: LiteParseConfig | undefined;
}

export interface PageComplexityStats {
  pageNumber: number;
  textLength: number;
  textCoverage: number;
  hasSubstantialImages: boolean;
  imageBlockCount: number;
  imageCoverage: number;
  largestImageCoverage: number;
  fullPageImage: boolean;
  uncovertedVectorArea?: number | undefined;
  isGarbled: boolean;
  pageArea: number;
  needsOcr: boolean;
  reasons: string[];
}

/** Response detailing the complexity estimation for a file */
export interface IsComplexResponse {
  complexity: PageComplexityStats[];
}

function createBaseLiteParseConfig(): LiteParseConfig {
  return {
    ocrLanguage: "",
    ocrEnabled: false,
    ocrServerUrl: undefined,
    ocrServerHeaders: [],
    tessdataPath: undefined,
    maxPages: 0,
    targetPages: undefined,
    dpi: 0,
    outputFormat: 0,
    preserveVerySmallText: false,
    password: undefined,
    quiet: false,
    numWorkers: 0,
    imageMode: 0,
    extractLinks: false,
    ocrFailureFatal: false,
    ocrHedgeDelaysMs: [],
    emitWordBoxes: false,
  };
}

export const LiteParseConfig: MessageFns<LiteParseConfig> = {
  encode(
    message: LiteParseConfig,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.ocrLanguage !== "") {
      writer.uint32(10).string(message.ocrLanguage);
    }
    if (message.ocrEnabled !== false) {
      writer.uint32(16).bool(message.ocrEnabled);
    }
    if (message.ocrServerUrl !== undefined) {
      writer.uint32(26).string(message.ocrServerUrl);
    }
    for (const v of message.ocrServerHeaders) {
      HttpHeader.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.tessdataPath !== undefined) {
      writer.uint32(42).string(message.tessdataPath);
    }
    if (message.maxPages !== 0) {
      writer.uint32(48).uint64(message.maxPages);
    }
    if (message.targetPages !== undefined) {
      writer.uint32(58).string(message.targetPages);
    }
    if (message.dpi !== 0) {
      writer.uint32(69).float(message.dpi);
    }
    if (message.outputFormat !== 0) {
      writer.uint32(72).int32(message.outputFormat);
    }
    if (message.preserveVerySmallText !== false) {
      writer.uint32(80).bool(message.preserveVerySmallText);
    }
    if (message.password !== undefined) {
      writer.uint32(90).string(message.password);
    }
    if (message.quiet !== false) {
      writer.uint32(96).bool(message.quiet);
    }
    if (message.numWorkers !== 0) {
      writer.uint32(104).uint64(message.numWorkers);
    }
    if (message.imageMode !== 0) {
      writer.uint32(112).int32(message.imageMode);
    }
    if (message.extractLinks !== false) {
      writer.uint32(120).bool(message.extractLinks);
    }
    if (message.ocrFailureFatal !== false) {
      writer.uint32(128).bool(message.ocrFailureFatal);
    }
    writer.uint32(138).fork();
    for (const v of message.ocrHedgeDelaysMs) {
      writer.uint64(v);
    }
    writer.join();
    if (message.emitWordBoxes !== false) {
      writer.uint32(144).bool(message.emitWordBoxes);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LiteParseConfig {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLiteParseConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ocrLanguage = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ocrEnabled = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ocrServerUrl = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ocrServerHeaders.push(
            HttpHeader.decode(reader, reader.uint32()),
          );
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.tessdataPath = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.maxPages = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.targetPages = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 69) {
            break;
          }

          message.dpi = reader.float();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.outputFormat = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.preserveVerySmallText = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.quiet = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.numWorkers = longToNumber(reader.uint64());
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.imageMode = reader.int32() as any;
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.extractLinks = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.ocrFailureFatal = reader.bool();
          continue;
        }
        case 17: {
          if (tag === 136) {
            message.ocrHedgeDelaysMs.push(longToNumber(reader.uint64()));

            continue;
          }

          if (tag === 138) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.ocrHedgeDelaysMs.push(longToNumber(reader.uint64()));
            }

            continue;
          }

          break;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.emitWordBoxes = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LiteParseConfig {
    return {
      ocrLanguage: isSet(object.ocrLanguage)
        ? globalThis.String(object.ocrLanguage)
        : isSet(object.ocr_language)
          ? globalThis.String(object.ocr_language)
          : "",
      ocrEnabled: isSet(object.ocrEnabled)
        ? globalThis.Boolean(object.ocrEnabled)
        : isSet(object.ocr_enabled)
          ? globalThis.Boolean(object.ocr_enabled)
          : false,
      ocrServerUrl: isSet(object.ocrServerUrl)
        ? globalThis.String(object.ocrServerUrl)
        : isSet(object.ocr_server_url)
          ? globalThis.String(object.ocr_server_url)
          : undefined,
      ocrServerHeaders: globalThis.Array.isArray(object?.ocrServerHeaders)
        ? object.ocrServerHeaders.map((e: any) => HttpHeader.fromJSON(e))
        : globalThis.Array.isArray(object?.ocr_server_headers)
          ? object.ocr_server_headers.map((e: any) => HttpHeader.fromJSON(e))
          : [],
      tessdataPath: isSet(object.tessdataPath)
        ? globalThis.String(object.tessdataPath)
        : isSet(object.tessdata_path)
          ? globalThis.String(object.tessdata_path)
          : undefined,
      maxPages: isSet(object.maxPages)
        ? globalThis.Number(object.maxPages)
        : isSet(object.max_pages)
          ? globalThis.Number(object.max_pages)
          : 0,
      targetPages: isSet(object.targetPages)
        ? globalThis.String(object.targetPages)
        : isSet(object.target_pages)
          ? globalThis.String(object.target_pages)
          : undefined,
      dpi: isSet(object.dpi) ? globalThis.Number(object.dpi) : 0,
      outputFormat: isSet(object.outputFormat)
        ? outputFormatFromJSON(object.outputFormat)
        : isSet(object.output_format)
          ? outputFormatFromJSON(object.output_format)
          : 0,
      preserveVerySmallText: isSet(object.preserveVerySmallText)
        ? globalThis.Boolean(object.preserveVerySmallText)
        : isSet(object.preserve_very_small_text)
          ? globalThis.Boolean(object.preserve_very_small_text)
          : false,
      password: isSet(object.password)
        ? globalThis.String(object.password)
        : undefined,
      quiet: isSet(object.quiet) ? globalThis.Boolean(object.quiet) : false,
      numWorkers: isSet(object.numWorkers)
        ? globalThis.Number(object.numWorkers)
        : isSet(object.num_workers)
          ? globalThis.Number(object.num_workers)
          : 0,
      imageMode: isSet(object.imageMode)
        ? imageModeFromJSON(object.imageMode)
        : isSet(object.image_mode)
          ? imageModeFromJSON(object.image_mode)
          : 0,
      extractLinks: isSet(object.extractLinks)
        ? globalThis.Boolean(object.extractLinks)
        : isSet(object.extract_links)
          ? globalThis.Boolean(object.extract_links)
          : false,
      ocrFailureFatal: isSet(object.ocrFailureFatal)
        ? globalThis.Boolean(object.ocrFailureFatal)
        : isSet(object.ocr_failure_fatal)
          ? globalThis.Boolean(object.ocr_failure_fatal)
          : false,
      ocrHedgeDelaysMs: globalThis.Array.isArray(object?.ocrHedgeDelaysMs)
        ? object.ocrHedgeDelaysMs.map((e: any) => globalThis.Number(e))
        : globalThis.Array.isArray(object?.ocr_hedge_delays_ms)
          ? object.ocr_hedge_delays_ms.map((e: any) => globalThis.Number(e))
          : [],
      emitWordBoxes: isSet(object.emitWordBoxes)
        ? globalThis.Boolean(object.emitWordBoxes)
        : isSet(object.emit_word_boxes)
          ? globalThis.Boolean(object.emit_word_boxes)
          : false,
    };
  },

  toJSON(message: LiteParseConfig): unknown {
    const obj: any = {};
    if (message.ocrLanguage !== "") {
      obj.ocrLanguage = message.ocrLanguage;
    }
    if (message.ocrEnabled !== false) {
      obj.ocrEnabled = message.ocrEnabled;
    }
    if (message.ocrServerUrl !== undefined) {
      obj.ocrServerUrl = message.ocrServerUrl;
    }
    if (message.ocrServerHeaders?.length) {
      obj.ocrServerHeaders = message.ocrServerHeaders.map((e) =>
        HttpHeader.toJSON(e),
      );
    }
    if (message.tessdataPath !== undefined) {
      obj.tessdataPath = message.tessdataPath;
    }
    if (message.maxPages !== 0) {
      obj.maxPages = Math.round(message.maxPages);
    }
    if (message.targetPages !== undefined) {
      obj.targetPages = message.targetPages;
    }
    if (message.dpi !== 0) {
      obj.dpi = message.dpi;
    }
    if (message.outputFormat !== 0) {
      obj.outputFormat = outputFormatToJSON(message.outputFormat);
    }
    if (message.preserveVerySmallText !== false) {
      obj.preserveVerySmallText = message.preserveVerySmallText;
    }
    if (message.password !== undefined) {
      obj.password = message.password;
    }
    if (message.quiet !== false) {
      obj.quiet = message.quiet;
    }
    if (message.numWorkers !== 0) {
      obj.numWorkers = Math.round(message.numWorkers);
    }
    if (message.imageMode !== 0) {
      obj.imageMode = imageModeToJSON(message.imageMode);
    }
    if (message.extractLinks !== false) {
      obj.extractLinks = message.extractLinks;
    }
    if (message.ocrFailureFatal !== false) {
      obj.ocrFailureFatal = message.ocrFailureFatal;
    }
    if (message.ocrHedgeDelaysMs?.length) {
      obj.ocrHedgeDelaysMs = message.ocrHedgeDelaysMs.map((e) => Math.round(e));
    }
    if (message.emitWordBoxes !== false) {
      obj.emitWordBoxes = message.emitWordBoxes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LiteParseConfig>, I>>(
    base?: I,
  ): LiteParseConfig {
    return LiteParseConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LiteParseConfig>, I>>(
    object: I,
  ): LiteParseConfig {
    const message = createBaseLiteParseConfig();
    message.ocrLanguage = object.ocrLanguage ?? "";
    message.ocrEnabled = object.ocrEnabled ?? false;
    message.ocrServerUrl = object.ocrServerUrl ?? undefined;
    message.ocrServerHeaders =
      object.ocrServerHeaders?.map((e) => HttpHeader.fromPartial(e)) || [];
    message.tessdataPath = object.tessdataPath ?? undefined;
    message.maxPages = object.maxPages ?? 0;
    message.targetPages = object.targetPages ?? undefined;
    message.dpi = object.dpi ?? 0;
    message.outputFormat = object.outputFormat ?? 0;
    message.preserveVerySmallText = object.preserveVerySmallText ?? false;
    message.password = object.password ?? undefined;
    message.quiet = object.quiet ?? false;
    message.numWorkers = object.numWorkers ?? 0;
    message.imageMode = object.imageMode ?? 0;
    message.extractLinks = object.extractLinks ?? false;
    message.ocrFailureFatal = object.ocrFailureFatal ?? false;
    message.ocrHedgeDelaysMs = object.ocrHedgeDelaysMs?.map((e) => e) || [];
    message.emitWordBoxes = object.emitWordBoxes ?? false;
    return message;
  },
};

function createBaseHttpHeader(): HttpHeader {
  return { name: "", value: "" };
}

export const HttpHeader: MessageFns<HttpHeader> = {
  encode(
    message: HttpHeader,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HttpHeader {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHttpHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HttpHeader {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: HttpHeader): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HttpHeader>, I>>(base?: I): HttpHeader {
    return HttpHeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HttpHeader>, I>>(
    object: I,
  ): HttpHeader {
    const message = createBaseHttpHeader();
    message.name = object.name ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseParseRequest(): ParseRequest {
  return { file: Buffer.alloc(0), config: undefined };
}

export const ParseRequest: MessageFns<ParseRequest> = {
  encode(
    message: ParseRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.file.length !== 0) {
      writer.uint32(10).bytes(message.file);
    }
    if (message.config !== undefined) {
      LiteParseConfig.encode(message.config, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ParseRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.config = LiteParseConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ParseRequest {
    return {
      file: isSet(object.file)
        ? Buffer.from(bytesFromBase64(object.file))
        : Buffer.alloc(0),
      config: isSet(object.config)
        ? LiteParseConfig.fromJSON(object.config)
        : undefined,
    };
  },

  toJSON(message: ParseRequest): unknown {
    const obj: any = {};
    if (message.file.length !== 0) {
      obj.file = base64FromBytes(message.file);
    }
    if (message.config !== undefined) {
      obj.config = LiteParseConfig.toJSON(message.config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ParseRequest>, I>>(
    base?: I,
  ): ParseRequest {
    return ParseRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ParseRequest>, I>>(
    object: I,
  ): ParseRequest {
    const message = createBaseParseRequest();
    message.file = object.file ?? Buffer.alloc(0);
    message.config =
      object.config !== undefined && object.config !== null
        ? LiteParseConfig.fromPartial(object.config)
        : undefined;
    return message;
  },
};

function createBaseScreenshotRequest(): ScreenshotRequest {
  return { file: Buffer.alloc(0), config: undefined };
}

export const ScreenshotRequest: MessageFns<ScreenshotRequest> = {
  encode(
    message: ScreenshotRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.file.length !== 0) {
      writer.uint32(10).bytes(message.file);
    }
    if (message.config !== undefined) {
      LiteParseConfig.encode(message.config, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScreenshotRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScreenshotRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.config = LiteParseConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScreenshotRequest {
    return {
      file: isSet(object.file)
        ? Buffer.from(bytesFromBase64(object.file))
        : Buffer.alloc(0),
      config: isSet(object.config)
        ? LiteParseConfig.fromJSON(object.config)
        : undefined,
    };
  },

  toJSON(message: ScreenshotRequest): unknown {
    const obj: any = {};
    if (message.file.length !== 0) {
      obj.file = base64FromBytes(message.file);
    }
    if (message.config !== undefined) {
      obj.config = LiteParseConfig.toJSON(message.config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScreenshotRequest>, I>>(
    base?: I,
  ): ScreenshotRequest {
    return ScreenshotRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScreenshotRequest>, I>>(
    object: I,
  ): ScreenshotRequest {
    const message = createBaseScreenshotRequest();
    message.file = object.file ?? Buffer.alloc(0);
    message.config =
      object.config !== undefined && object.config !== null
        ? LiteParseConfig.fromPartial(object.config)
        : undefined;
    return message;
  },
};

function createBaseTextItem(): TextItem {
  return { text: "", x: 0, y: 0, width: 0, height: 0 };
}

export const TextItem: MessageFns<TextItem> = {
  encode(
    message: TextItem,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    if (message.x !== 0) {
      writer.uint32(21).float(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(29).float(message.y);
    }
    if (message.width !== 0) {
      writer.uint32(37).float(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(45).float(message.height);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TextItem {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTextItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.x = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.y = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 37) {
            break;
          }

          message.width = reader.float();
          continue;
        }
        case 5: {
          if (tag !== 45) {
            break;
          }

          message.height = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TextItem {
    return {
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
    };
  },

  toJSON(message: TextItem): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.x !== 0) {
      obj.x = message.x;
    }
    if (message.y !== 0) {
      obj.y = message.y;
    }
    if (message.width !== 0) {
      obj.width = message.width;
    }
    if (message.height !== 0) {
      obj.height = message.height;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TextItem>, I>>(base?: I): TextItem {
    return TextItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TextItem>, I>>(object: I): TextItem {
    const message = createBaseTextItem();
    message.text = object.text ?? "";
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    return message;
  },
};

function createBaseParsedPage(): ParsedPage {
  return { pageNumber: 0, pageWidth: 0, pageHeight: 0, textItems: [] };
}

export const ParsedPage: MessageFns<ParsedPage> = {
  encode(
    message: ParsedPage,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.pageNumber !== 0) {
      writer.uint32(8).uint32(message.pageNumber);
    }
    if (message.pageWidth !== 0) {
      writer.uint32(21).float(message.pageWidth);
    }
    if (message.pageHeight !== 0) {
      writer.uint32(29).float(message.pageHeight);
    }
    for (const v of message.textItems) {
      TextItem.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ParsedPage {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParsedPage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pageNumber = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.pageWidth = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.pageHeight = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.textItems.push(TextItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ParsedPage {
    return {
      pageNumber: isSet(object.pageNumber)
        ? globalThis.Number(object.pageNumber)
        : isSet(object.page_number)
          ? globalThis.Number(object.page_number)
          : 0,
      pageWidth: isSet(object.pageWidth)
        ? globalThis.Number(object.pageWidth)
        : isSet(object.page_width)
          ? globalThis.Number(object.page_width)
          : 0,
      pageHeight: isSet(object.pageHeight)
        ? globalThis.Number(object.pageHeight)
        : isSet(object.page_height)
          ? globalThis.Number(object.page_height)
          : 0,
      textItems: globalThis.Array.isArray(object?.textItems)
        ? object.textItems.map((e: any) => TextItem.fromJSON(e))
        : globalThis.Array.isArray(object?.text_items)
          ? object.text_items.map((e: any) => TextItem.fromJSON(e))
          : [],
    };
  },

  toJSON(message: ParsedPage): unknown {
    const obj: any = {};
    if (message.pageNumber !== 0) {
      obj.pageNumber = Math.round(message.pageNumber);
    }
    if (message.pageWidth !== 0) {
      obj.pageWidth = message.pageWidth;
    }
    if (message.pageHeight !== 0) {
      obj.pageHeight = message.pageHeight;
    }
    if (message.textItems?.length) {
      obj.textItems = message.textItems.map((e) => TextItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ParsedPage>, I>>(base?: I): ParsedPage {
    return ParsedPage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ParsedPage>, I>>(
    object: I,
  ): ParsedPage {
    const message = createBaseParsedPage();
    message.pageNumber = object.pageNumber ?? 0;
    message.pageWidth = object.pageWidth ?? 0;
    message.pageHeight = object.pageHeight ?? 0;
    message.textItems =
      object.textItems?.map((e) => TextItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseParseResponse(): ParseResponse {
  return { text: "", pages: [] };
}

export const ParseResponse: MessageFns<ParseResponse> = {
  encode(
    message: ParseResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.text !== "") {
      writer.uint32(10).string(message.text);
    }
    for (const v of message.pages) {
      ParsedPage.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ParseResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pages.push(ParsedPage.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ParseResponse {
    return {
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      pages: globalThis.Array.isArray(object?.pages)
        ? object.pages.map((e: any) => ParsedPage.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ParseResponse): unknown {
    const obj: any = {};
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.pages?.length) {
      obj.pages = message.pages.map((e) => ParsedPage.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ParseResponse>, I>>(
    base?: I,
  ): ParseResponse {
    return ParseResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ParseResponse>, I>>(
    object: I,
  ): ParseResponse {
    const message = createBaseParseResponse();
    message.text = object.text ?? "";
    message.pages = object.pages?.map((e) => ParsedPage.fromPartial(e)) || [];
    return message;
  },
};

function createBaseScreenshotPage(): ScreenshotPage {
  return {
    imageBytes: Buffer.alloc(0),
    pageNumber: 0,
    height: 0,
    width: 0,
    mimeType: "",
  };
}

export const ScreenshotPage: MessageFns<ScreenshotPage> = {
  encode(
    message: ScreenshotPage,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.imageBytes.length !== 0) {
      writer.uint32(10).bytes(message.imageBytes);
    }
    if (message.pageNumber !== 0) {
      writer.uint32(16).uint32(message.pageNumber);
    }
    if (message.height !== 0) {
      writer.uint32(24).uint32(message.height);
    }
    if (message.width !== 0) {
      writer.uint32(32).uint32(message.width);
    }
    if (message.mimeType !== "") {
      writer.uint32(42).string(message.mimeType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ScreenshotPage {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScreenshotPage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.imageBytes = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pageNumber = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.height = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.width = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.mimeType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScreenshotPage {
    return {
      imageBytes: isSet(object.imageBytes)
        ? Buffer.from(bytesFromBase64(object.imageBytes))
        : isSet(object.image_bytes)
          ? Buffer.from(bytesFromBase64(object.image_bytes))
          : Buffer.alloc(0),
      pageNumber: isSet(object.pageNumber)
        ? globalThis.Number(object.pageNumber)
        : isSet(object.page_number)
          ? globalThis.Number(object.page_number)
          : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      mimeType: isSet(object.mimeType)
        ? globalThis.String(object.mimeType)
        : isSet(object.mime_type)
          ? globalThis.String(object.mime_type)
          : "",
    };
  },

  toJSON(message: ScreenshotPage): unknown {
    const obj: any = {};
    if (message.imageBytes.length !== 0) {
      obj.imageBytes = base64FromBytes(message.imageBytes);
    }
    if (message.pageNumber !== 0) {
      obj.pageNumber = Math.round(message.pageNumber);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    if (message.width !== 0) {
      obj.width = Math.round(message.width);
    }
    if (message.mimeType !== "") {
      obj.mimeType = message.mimeType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScreenshotPage>, I>>(
    base?: I,
  ): ScreenshotPage {
    return ScreenshotPage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScreenshotPage>, I>>(
    object: I,
  ): ScreenshotPage {
    const message = createBaseScreenshotPage();
    message.imageBytes = object.imageBytes ?? Buffer.alloc(0);
    message.pageNumber = object.pageNumber ?? 0;
    message.height = object.height ?? 0;
    message.width = object.width ?? 0;
    message.mimeType = object.mimeType ?? "";
    return message;
  },
};

function createBaseScreenshotResponse(): ScreenshotResponse {
  return { screenshots: [] };
}

export const ScreenshotResponse: MessageFns<ScreenshotResponse> = {
  encode(
    message: ScreenshotResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.screenshots) {
      ScreenshotPage.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): ScreenshotResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseScreenshotResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.screenshots.push(
            ScreenshotPage.decode(reader, reader.uint32()),
          );
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ScreenshotResponse {
    return {
      screenshots: globalThis.Array.isArray(object?.screenshots)
        ? object.screenshots.map((e: any) => ScreenshotPage.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ScreenshotResponse): unknown {
    const obj: any = {};
    if (message.screenshots?.length) {
      obj.screenshots = message.screenshots.map((e) =>
        ScreenshotPage.toJSON(e),
      );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ScreenshotResponse>, I>>(
    base?: I,
  ): ScreenshotResponse {
    return ScreenshotResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ScreenshotResponse>, I>>(
    object: I,
  ): ScreenshotResponse {
    const message = createBaseScreenshotResponse();
    message.screenshots =
      object.screenshots?.map((e) => ScreenshotPage.fromPartial(e)) || [];
    return message;
  },
};

function createBaseIsComplexRequest(): IsComplexRequest {
  return { file: Buffer.alloc(0), config: undefined };
}

export const IsComplexRequest: MessageFns<IsComplexRequest> = {
  encode(
    message: IsComplexRequest,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.file.length !== 0) {
      writer.uint32(10).bytes(message.file);
    }
    if (message.config !== undefined) {
      LiteParseConfig.encode(message.config, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IsComplexRequest {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIsComplexRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.file = Buffer.from(reader.bytes());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.config = LiteParseConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IsComplexRequest {
    return {
      file: isSet(object.file)
        ? Buffer.from(bytesFromBase64(object.file))
        : Buffer.alloc(0),
      config: isSet(object.config)
        ? LiteParseConfig.fromJSON(object.config)
        : undefined,
    };
  },

  toJSON(message: IsComplexRequest): unknown {
    const obj: any = {};
    if (message.file.length !== 0) {
      obj.file = base64FromBytes(message.file);
    }
    if (message.config !== undefined) {
      obj.config = LiteParseConfig.toJSON(message.config);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IsComplexRequest>, I>>(
    base?: I,
  ): IsComplexRequest {
    return IsComplexRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IsComplexRequest>, I>>(
    object: I,
  ): IsComplexRequest {
    const message = createBaseIsComplexRequest();
    message.file = object.file ?? Buffer.alloc(0);
    message.config =
      object.config !== undefined && object.config !== null
        ? LiteParseConfig.fromPartial(object.config)
        : undefined;
    return message;
  },
};

function createBasePageComplexityStats(): PageComplexityStats {
  return {
    pageNumber: 0,
    textLength: 0,
    textCoverage: 0,
    hasSubstantialImages: false,
    imageBlockCount: 0,
    imageCoverage: 0,
    largestImageCoverage: 0,
    fullPageImage: false,
    uncovertedVectorArea: undefined,
    isGarbled: false,
    pageArea: 0,
    needsOcr: false,
    reasons: [],
  };
}

export const PageComplexityStats: MessageFns<PageComplexityStats> = {
  encode(
    message: PageComplexityStats,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.pageNumber !== 0) {
      writer.uint32(8).uint32(message.pageNumber);
    }
    if (message.textLength !== 0) {
      writer.uint32(16).uint64(message.textLength);
    }
    if (message.textCoverage !== 0) {
      writer.uint32(29).float(message.textCoverage);
    }
    if (message.hasSubstantialImages !== false) {
      writer.uint32(32).bool(message.hasSubstantialImages);
    }
    if (message.imageBlockCount !== 0) {
      writer.uint32(40).uint32(message.imageBlockCount);
    }
    if (message.imageCoverage !== 0) {
      writer.uint32(53).float(message.imageCoverage);
    }
    if (message.largestImageCoverage !== 0) {
      writer.uint32(61).float(message.largestImageCoverage);
    }
    if (message.fullPageImage !== false) {
      writer.uint32(64).bool(message.fullPageImage);
    }
    if (message.uncovertedVectorArea !== undefined) {
      writer.uint32(77).float(message.uncovertedVectorArea);
    }
    if (message.isGarbled !== false) {
      writer.uint32(80).bool(message.isGarbled);
    }
    if (message.pageArea !== 0) {
      writer.uint32(93).float(message.pageArea);
    }
    if (message.needsOcr !== false) {
      writer.uint32(96).bool(message.needsOcr);
    }
    for (const v of message.reasons) {
      writer.uint32(106).string(v!);
    }
    return writer;
  },

  decode(
    input: BinaryReader | Uint8Array,
    length?: number,
  ): PageComplexityStats {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePageComplexityStats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pageNumber = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.textLength = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 29) {
            break;
          }

          message.textCoverage = reader.float();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.hasSubstantialImages = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.imageBlockCount = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 53) {
            break;
          }

          message.imageCoverage = reader.float();
          continue;
        }
        case 7: {
          if (tag !== 61) {
            break;
          }

          message.largestImageCoverage = reader.float();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.fullPageImage = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 77) {
            break;
          }

          message.uncovertedVectorArea = reader.float();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.isGarbled = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 93) {
            break;
          }

          message.pageArea = reader.float();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.needsOcr = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.reasons.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PageComplexityStats {
    return {
      pageNumber: isSet(object.pageNumber)
        ? globalThis.Number(object.pageNumber)
        : isSet(object.page_number)
          ? globalThis.Number(object.page_number)
          : 0,
      textLength: isSet(object.textLength)
        ? globalThis.Number(object.textLength)
        : isSet(object.text_length)
          ? globalThis.Number(object.text_length)
          : 0,
      textCoverage: isSet(object.textCoverage)
        ? globalThis.Number(object.textCoverage)
        : isSet(object.text_coverage)
          ? globalThis.Number(object.text_coverage)
          : 0,
      hasSubstantialImages: isSet(object.hasSubstantialImages)
        ? globalThis.Boolean(object.hasSubstantialImages)
        : isSet(object.has_substantial_images)
          ? globalThis.Boolean(object.has_substantial_images)
          : false,
      imageBlockCount: isSet(object.imageBlockCount)
        ? globalThis.Number(object.imageBlockCount)
        : isSet(object.image_block_count)
          ? globalThis.Number(object.image_block_count)
          : 0,
      imageCoverage: isSet(object.imageCoverage)
        ? globalThis.Number(object.imageCoverage)
        : isSet(object.image_coverage)
          ? globalThis.Number(object.image_coverage)
          : 0,
      largestImageCoverage: isSet(object.largestImageCoverage)
        ? globalThis.Number(object.largestImageCoverage)
        : isSet(object.largest_image_coverage)
          ? globalThis.Number(object.largest_image_coverage)
          : 0,
      fullPageImage: isSet(object.fullPageImage)
        ? globalThis.Boolean(object.fullPageImage)
        : isSet(object.full_page_image)
          ? globalThis.Boolean(object.full_page_image)
          : false,
      uncovertedVectorArea: isSet(object.uncovertedVectorArea)
        ? globalThis.Number(object.uncovertedVectorArea)
        : isSet(object.uncoverted_vector_area)
          ? globalThis.Number(object.uncoverted_vector_area)
          : undefined,
      isGarbled: isSet(object.isGarbled)
        ? globalThis.Boolean(object.isGarbled)
        : isSet(object.is_garbled)
          ? globalThis.Boolean(object.is_garbled)
          : false,
      pageArea: isSet(object.pageArea)
        ? globalThis.Number(object.pageArea)
        : isSet(object.page_area)
          ? globalThis.Number(object.page_area)
          : 0,
      needsOcr: isSet(object.needsOcr)
        ? globalThis.Boolean(object.needsOcr)
        : isSet(object.needs_ocr)
          ? globalThis.Boolean(object.needs_ocr)
          : false,
      reasons: globalThis.Array.isArray(object?.reasons)
        ? object.reasons.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: PageComplexityStats): unknown {
    const obj: any = {};
    if (message.pageNumber !== 0) {
      obj.pageNumber = Math.round(message.pageNumber);
    }
    if (message.textLength !== 0) {
      obj.textLength = Math.round(message.textLength);
    }
    if (message.textCoverage !== 0) {
      obj.textCoverage = message.textCoverage;
    }
    if (message.hasSubstantialImages !== false) {
      obj.hasSubstantialImages = message.hasSubstantialImages;
    }
    if (message.imageBlockCount !== 0) {
      obj.imageBlockCount = Math.round(message.imageBlockCount);
    }
    if (message.imageCoverage !== 0) {
      obj.imageCoverage = message.imageCoverage;
    }
    if (message.largestImageCoverage !== 0) {
      obj.largestImageCoverage = message.largestImageCoverage;
    }
    if (message.fullPageImage !== false) {
      obj.fullPageImage = message.fullPageImage;
    }
    if (message.uncovertedVectorArea !== undefined) {
      obj.uncovertedVectorArea = message.uncovertedVectorArea;
    }
    if (message.isGarbled !== false) {
      obj.isGarbled = message.isGarbled;
    }
    if (message.pageArea !== 0) {
      obj.pageArea = message.pageArea;
    }
    if (message.needsOcr !== false) {
      obj.needsOcr = message.needsOcr;
    }
    if (message.reasons?.length) {
      obj.reasons = message.reasons;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PageComplexityStats>, I>>(
    base?: I,
  ): PageComplexityStats {
    return PageComplexityStats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PageComplexityStats>, I>>(
    object: I,
  ): PageComplexityStats {
    const message = createBasePageComplexityStats();
    message.pageNumber = object.pageNumber ?? 0;
    message.textLength = object.textLength ?? 0;
    message.textCoverage = object.textCoverage ?? 0;
    message.hasSubstantialImages = object.hasSubstantialImages ?? false;
    message.imageBlockCount = object.imageBlockCount ?? 0;
    message.imageCoverage = object.imageCoverage ?? 0;
    message.largestImageCoverage = object.largestImageCoverage ?? 0;
    message.fullPageImage = object.fullPageImage ?? false;
    message.uncovertedVectorArea = object.uncovertedVectorArea ?? undefined;
    message.isGarbled = object.isGarbled ?? false;
    message.pageArea = object.pageArea ?? 0;
    message.needsOcr = object.needsOcr ?? false;
    message.reasons = object.reasons?.map((e) => e) || [];
    return message;
  },
};

function createBaseIsComplexResponse(): IsComplexResponse {
  return { complexity: [] };
}

export const IsComplexResponse: MessageFns<IsComplexResponse> = {
  encode(
    message: IsComplexResponse,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    for (const v of message.complexity) {
      PageComplexityStats.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IsComplexResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIsComplexResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.complexity.push(
            PageComplexityStats.decode(reader, reader.uint32()),
          );
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IsComplexResponse {
    return {
      complexity: globalThis.Array.isArray(object?.complexity)
        ? object.complexity.map((e: any) => PageComplexityStats.fromJSON(e))
        : [],
    };
  },

  toJSON(message: IsComplexResponse): unknown {
    const obj: any = {};
    if (message.complexity?.length) {
      obj.complexity = message.complexity.map((e) =>
        PageComplexityStats.toJSON(e),
      );
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IsComplexResponse>, I>>(
    base?: I,
  ): IsComplexResponse {
    return IsComplexResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IsComplexResponse>, I>>(
    object: I,
  ): IsComplexResponse {
    const message = createBaseIsComplexResponse();
    message.complexity =
      object.complexity?.map((e) => PageComplexityStats.fromPartial(e)) || [];
    return message;
  },
};

/** The Parser service definition. */
export type ParserServiceService = typeof ParserServiceService;
export const ParserServiceService = {
  /** Parse a file */
  parse: {
    path: "/parser.ParserService/Parse" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ParseRequest): Buffer =>
      Buffer.from(ParseRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ParseRequest =>
      ParseRequest.decode(value),
    responseSerialize: (value: ParseResponse): Buffer =>
      Buffer.from(ParseResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ParseResponse =>
      ParseResponse.decode(value),
  },
  /** Screenshot the pages of a PDF file */
  screenshot: {
    path: "/parser.ParserService/Screenshot" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ScreenshotRequest): Buffer =>
      Buffer.from(ScreenshotRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ScreenshotRequest =>
      ScreenshotRequest.decode(value),
    responseSerialize: (value: ScreenshotResponse): Buffer =>
      Buffer.from(ScreenshotResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ScreenshotResponse =>
      ScreenshotResponse.decode(value),
  },
  /** Estimate the complexity of a file and the need for OCR */
  isComplex: {
    path: "/parser.ParserService/IsComplex" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: IsComplexRequest): Buffer =>
      Buffer.from(IsComplexRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): IsComplexRequest =>
      IsComplexRequest.decode(value),
    responseSerialize: (value: IsComplexResponse): Buffer =>
      Buffer.from(IsComplexResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): IsComplexResponse =>
      IsComplexResponse.decode(value),
  },
} as const;

export interface ParserServiceServer extends UntypedServiceImplementation {
  /** Parse a file */
  parse: handleUnaryCall<ParseRequest, ParseResponse>;
  /** Screenshot the pages of a PDF file */
  screenshot: handleUnaryCall<ScreenshotRequest, ScreenshotResponse>;
  /** Estimate the complexity of a file and the need for OCR */
  isComplex: handleUnaryCall<IsComplexRequest, IsComplexResponse>;
}

export interface ParserServiceClient extends Client {
  /** Parse a file */
  parse(
    request: ParseRequest,
    callback: (error: ServiceError | null, response: ParseResponse) => void,
  ): ClientUnaryCall;
  parse(
    request: ParseRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ParseResponse) => void,
  ): ClientUnaryCall;
  parse(
    request: ParseRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ParseResponse) => void,
  ): ClientUnaryCall;
  /** Screenshot the pages of a PDF file */
  screenshot(
    request: ScreenshotRequest,
    callback: (
      error: ServiceError | null,
      response: ScreenshotResponse,
    ) => void,
  ): ClientUnaryCall;
  screenshot(
    request: ScreenshotRequest,
    metadata: Metadata,
    callback: (
      error: ServiceError | null,
      response: ScreenshotResponse,
    ) => void,
  ): ClientUnaryCall;
  screenshot(
    request: ScreenshotRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (
      error: ServiceError | null,
      response: ScreenshotResponse,
    ) => void,
  ): ClientUnaryCall;
  /** Estimate the complexity of a file and the need for OCR */
  isComplex(
    request: IsComplexRequest,
    callback: (error: ServiceError | null, response: IsComplexResponse) => void,
  ): ClientUnaryCall;
  isComplex(
    request: IsComplexRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: IsComplexResponse) => void,
  ): ClientUnaryCall;
  isComplex(
    request: IsComplexRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: IsComplexResponse) => void,
  ): ClientUnaryCall;
}

export const ParserServiceClient = makeGenericClientConstructor(
  ParserServiceService,
  "parser.ParserService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): ParserServiceClient;
  service: typeof ParserServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin =
  Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin
  ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & {
      [K in Exclude<keyof I, KeysOfUnion<P>>]: never;
    };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
